#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\DependencyInjection\Compiler\CommandPass;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Symfony\Component\Dotenv\Dotenv;

$dotenv = new Dotenv();
$dotenv->loadEnv(__DIR__.'/.env');

$container = new ContainerBuilder();
$container->addCompilerPass(new CommandPass());
$loader = new YamlFileLoader($container, new FileLocator(__DIR__.'/config'));
$loader->load('services.yaml');
$container->compile(true);

$application = $container->get(Application::class);
$application->run();
